# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=7)),
                ('recipients', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Thread'),
        ),
    ]
