# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_sender', models.CharField(max_length=7)),
                ('db_recipients', models.TextField()),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('db_date_sent', models.DateTimeField(verbose_name='date sent')),
                ('db_content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='text',
            name='db_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Thread'),
        ),
    ]
